create table company_entity (id_company integer generated by default as identity, name_company varchar(255), primary key (id_company))
create table product_entity (id_product integer generated by default as identity, name_product varchar(255), id_company integer, primary key (id_product))
alter table product_entity add constraint FKp91ctpejcxdpjs1r8prodlhjk foreign key (id_company) references company_entity
