create table es_accessories (id_accessories integer generated by default as identity, name_accessories varchar(255), id_product_accessories integer, primary key (id_accessories))
create table es_product (id_product integer generated by default as identity, name_product varchar(255), primary key (id_product))
alter table es_accessories add constraint FK5yr774oeuqugfu50rt51m21kb foreign key (id_product_accessories) references es_product
