
insert into ES_PRODUCT (ID_COMPANY, NAME_COMPANY)
values(1, 'Apple');
insert into ES_PRODUCT (ID_COMPANY, NAME_COMPANY)
values(2, 'Samsung');



insert into ES_ACCESSORIES (ID_ACCESSORIES, NAME_ACCESSORIES, ID_COMPANY)
values(1, 'Iphone 7', 1);
insert into ES_ACCESSORIES (ID_ACCESSORIES, NAME_ACCESSORIES, ID_COMPANY)
values(2, 'IPadPro', 1);
insert into ES_ACCESSORIES (ID_ACCESSORIES, NAME_ACCESSORIES, ID_COMPANY)
values(3, 'GalaxyJ7', 2);
insert into ES_ACCESSORIES (ID_ACCESSORIES, NAME_ACCESSORIES, ID_COMPANY)
values(4, 'GalaxyTabA', 2);

