
insert into ES_PRODUCT (ID_PRODUCT, NAME_PRODUCT)
values(1, 'PROD-01');
insert into ES_PRODUCT (ID_PRODUCT, NAME_PRODUCT)
values(2, 'PROD-02');



insert into ES_ACCESSORIES (ID_ACCESSORIES, NAME_ACCESSORIES, ID_PRODUCT)
values(1, 'ACCESS-01', 1);
insert into ES_ACCESSORIES (ID_ACCESSORIES, NAME_ACCESSORIES, ID_PRODUCT)
values(2, 'ACCESS-02', 1);
insert into ES_ACCESSORIES (ID_ACCESSORIES, NAME_ACCESSORIES, ID_PRODUCT)
values(3, 'ACCESS-03', 2);
insert into ES_ACCESSORIES (ID_ACCESSORIES, NAME_ACCESSORIES, ID_PRODUCT)
values(4, 'ACCESS-04', 2);

