
-- h2 Database


DROP TABLE IF EXISTS COMPANY_ENTITY;

create table COMPANY_ENTITY (
   ID_COMPANY BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME_COMPANY varchar(100) NOT NULL
);



DROP TABLE IF EXISTS PRODUCT_ENTITY;

create table PRODUCT_ENTITY (
   ID_PRODUCT BIGINT AUTO_INCREMENT PRIMARY KEY,
   ID_COMPANY BIGINT,
   NAME_PRODUCT varchar(100) NOT NULL,
   FOREIGN KEY (ID_COMPANY) REFERENCES COMPANY_ENTITY (ID_COMPANY)
);

--COMMENT ON COLUMN PRODUCT_ENTITY.ID_PRODUCT IS 'Preferred way to contact with employee';


-- drop table PRODUCT_ENTITY;
-- select * from PRODUCT_ENTITY;


