
-- h2 Database


DROP TABLE IF EXISTS ES_PRODUCT;

create table ES_PRODUCT (
   ID_PRODUCT BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME_PRODUCT varchar(100) NOT NULL
);



DROP TABLE IF EXISTS ES_ACCESSORIES;

create table ES_ACCESSORIES (
   ID_ACCESSORIES BIGINT AUTO_INCREMENT PRIMARY KEY,
   ID_PRODUCT_ACCESSORIES BIGINT,
   NAME_ACCESSORIES varchar(100) NOT NULL,
   --PRICE_ACCESSORIES NUMBER(6),
   --DATE_CREATION_ACCESSORIES DATE,
	
   -- FOREIGN KEY definition is optional for hibernate mapping;
   FOREIGN KEY (ID_PRODUCT_ACCESSORIES) REFERENCES ES_PRODUCT (ID_PRODUCT)
);

--COMMENT ON COLUMN ES_ACCESSORIES.ID_ACCESSORIES IS 'Preferred way to contact with employee';


-- drop table ES_ACCESSORIES;
-- select * from ES_ACCESSORIES;



DROP TABLE IF EXISTS ES_REVIEW;

CREATE TABLE ES_REVIEW (
	ID_REVIEW NUMBER(10) NOT NULL,
	ID_PRODUCT_REVIEW NUMBER(10) NOT NULL references ES_PRODUCT,
	STAR_REVIEW INT,
	--COMMENT_REVIEW varchar(100),
	--AUTHOR_REVIEW varchar(100),
	CONSTRAINT REVIEW_PK PRIMARY KEY (ID_REVIEW)
);


