
-- h2 Database


DROP TABLE IF EXISTS ES_PRODUCT;

create table ES_PRODUCT (
   ID_COMPANY BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME_COMPANY varchar(100) NOT NULL
);



DROP TABLE IF EXISTS ES_ACCESSORIES;

create table ES_ACCESSORIES (
   ID_PRODUCT BIGINT AUTO_INCREMENT PRIMARY KEY,
   ID_COMPANY BIGINT,
   NAME_PRODUCT varchar(100) NOT NULL,
   -- FOREIGN KEY definition is optional;
   FOREIGN KEY (ID_COMPANY) REFERENCES ES_PRODUCT (ID_COMPANY)
);

--COMMENT ON COLUMN ES_ACCESSORIES.ID_PRODUCT IS 'Preferred way to contact with employee';


-- drop table ES_ACCESSORIES;
-- select * from ES_ACCESSORIES;


